README.md
The aforementioned import was missing from the example.
=> fix($readme): Added combineReducers to example

__tests__/__snapshots__/connectRoutes.js.snap, __tests__/connectRoutes.js, docs/connectRoutes.md, src/connectRoutes.js, src/flow-types.js, src/index.js, src/pure-utils/createThunk.js
This PR is meant to continue the discussion of how to best handle a use case like Immutable.js, where the state shape of the app differs from what this lib expects. If you like what I've done here then by all means let's get it merged, but I'm also open to any and all feedback. Ultimately I really just want to be able to use this for my own projects which happen to use Immutable, but this change would also help anyone else dealing with a different state shape.
This came out of the discussion in #20, but basically it would help widespread adoption of this lib if it was not dependent on using plain objects for your state shape.
* **New options:** `selectLocationState` and `selectTitleState`. These are both functions that replace the use case of `location` and `title` options.
Previously the …
=> Support arbitrary state shapes using selectLocationState

__tests__/pure-utils.js, src/pure-utils/actionToPath.js
An empty pathname can be returned when the route map contains a path
with a single optional parameter such as {FOO: '/:foo?'} and an action
is supplied with the optional parameter undefined in the payload
such as {type: 'FOO', payload: {foo: undefined}}.
Previously, the pathname returned would be an empty string however the
History package treats empty paths as '/' so history.listen() handler
immediately dispatches a new action to change the location to '/'. 
This commit ensures that any empty pathname is converted to '/' before
being returned which prevents the double dispatch further on.
=> Prevent actionToPath from returning an empty pathname

README.md, docs/connectRoutes.md, docs/server-rendering.md
This adds some comments to example code snippets where the enhancer and middleware appear in order to clarify the importance of ordering them correctly within the `compose` block.  Also adds a small section to the `connectRoutes` doc about the return values.
This should hopefully avoid confusion for others in the future. 
(per: https://github.com/faceyspacey/redux-first-router/issues/60)
=> docs($docs): update docs to be clear about importance of enhancer order

__tests__/pure-utils.js, src/pure-utils/pathToAction.js
In certain route configurations (ex., `/my/path(.*)`), a route parameter may be a blank string. The existing code uses `isNaN()` to check if the parameter is numeric, and then parse it as a float. However, `isNaN('')` is `false`, but `parseFloat('')` is `NaN`, meaning that blank parameters would be converted to `NaN`.  (See [MDN's writeup on confusing behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Confusing_special-case_behavior).)
This manifested itself in the browser - for paths like `/my/path(.*)`, visiting `/my/path` would change the URL shown in the browser to `/my/pathNaN`.
=> fix($pathToAction): recognize blank string parameters as NaN

src/connectRoutes.js, src/pure-utils/attemptCallRouteThunk.js
`attemptCallRouteThunk` accessed the location state via `getState().location` which doesn't work with
custom locations in the state, instead `selectLocationState` must be passed to it and used
=> fix: fix location access bug in attemptCallRouteThunk

__tests__/__snapshots__/pure-utils.js.snap, __tests__/action-creators.js, __tests__/connectRoutes.js, __tests__/createLocationReducer.js, __tests__/pure-utils.js, package.json, src/connectRoutes.js, src/pure-utils/pathToAction.js
Added `basename` stripping to get the correct matching between map and URL. Also I push above the `option` initialization (from side effects part) to prevent it been uninitialized between the creation of `connectRoute` and the first initial action dispatching. Otherwise `getOption` returns `undefined` when the first route do its job. The original `history` removed from deps completely.
_Notice here:_
test snapsot **'nestHistory formats simplified history object for action + state'** was changed by me because all enrties have real value in key property after updated to our rudy-history. Please make sure I was right when I change this snapshot, may be, I don't understand smth...
=> Fixes for SEO with basename

__test-helpers__/setupThunk.js, __tests__/connectRoutes.js, package.json, src/connectRoutes.js, src/pure-utils/isRedirectAction.js, yarn.lock
`onAfterChange` is erroneously called when a routethunk dispatches a redirect action - this can
cause some undesired logic to executue.  This detects redirect actions in the executed routeThunks, and appropriately skips `onAfterChange` in that event.
#96
=> fix($thunks): Skip `onAfterChange` when route thunks dispatch a redirect

src/index.js
Fixes #115 by adding the flow annotation to the index file.
I am not sure whether this should be a major version release. Given all the types at the moment are exported as 'any', this change could break consumers using flow.
=> fix(flow types export): fixes export of types by adding flow annotation to index file

src/connectRoutes.js
In middleware function, it uses <code>store.getState().location</code> which doesn't work with custom locations.
It should use <code>selectLocationState(store.getState())</code> instead.
Though I changed one line, eslint automatically fixed some code.
=> fix($middleware): Fix location access bug of NotFoundAction

src/flow-types.js, src/pure-utils/pathToAction.js
Allows user to configure routes map to dispatch additional meta information in the aciton when a
route is matched.
Could this get squeezed in? It would be very helpful in tracking intermediate routing states (as brought up in Gitter chat)
=> feat($routeMap): Accept meta information in routesMap

docs/server-rendering.md
Redirect did not account for search which means that if a redirect contained a query parameter the query parameter was removed.
=> Update server-rendering.md: Correct redirect

__tests__/connectRoutes.js, src/connectRoutes.js
this fixes #265, It took me a little while to find the time to put this in, let me know if I have missed anything.
=> ensures that the querySerializer is used on the initial action so that query params appear during the initial  call

docs/action.md, docs/addRoutes.md, docs/blocking-navigation.md, docs/connectRoutes.md, docs/low-level-api.md, docs/url-parsing.md, examples/pathlessRoutes.js
Moving this from https://github.com/ScriptedAlchemy/redux-first-router/pull/32 now that @ScriptedAlchemy is a maintainer :)
I've made this PR into `rudy`, since I understand you are about to consolidate the latest pre-rewrite RFR (`rudy`) into the `master` branch where people will be able to easily find the docs. Is that right?
The changes made between what was is on the `master` branch and what is available on the `next` and `rudy` branches (and corresponding tags) were announced in the README in the [Road to Rudy](https://github.com/faceyspacey/redux-first-router#road-to-rudy) section.
Basically what I've done here is consolidate all that information (from that list of changes, comments on various issues announcing them, flow types, etc) and update the main docs folder so that it is a …
=> Update documentation with the changes in the next and rudy branches/tags

.snyk
They are all introduced via semantic-release/npm (latest versions), and therefore not an issue in production. I'd say they are both very low risk in development.
- https://github.com/isaacs/chownr/issues/14
- https://github.com/sindresorhus/mem/issues/14
=> Ignore vulnerabilities detected by skyk that exist in development only

README.md, docs/connectRoutes.md, docs/reducer.md, src/flow-types.js, src/pure-utils/pathToAction.js
Context: #292 
This adds a `coerceNumbers` flag to the RouteObject that is **false by default**.
Why implement it this way? Why not just take out this behavior entirely?
1. Type coercion should not be done without explicit user opt-in (IMO). It can lead to unexpected behavior & bugs.
2. However, parsing integers in a URL still feels useful sometimes. I used to use [this package](https://www.npmjs.com/package/express-query-int) in Express, why shouldn't Rudy have something similar?
3. If users are migrating to Rudy from the old master branch, and they relied on the old behavior, keeping this as an option gives them an easier migration path. Simply enable this flag on the routes where you need it.
@ScriptedAlchemy let me know what you think!
=> Integer coercion fix for Rudy

README.md, docs/connectRoutes.md, docs/reducer.md, src/flow-types.js, src/pure-utils/pathToAction.js
Add a coerceNumbers flag to *allow authors* to prevent routes like `000123` from being converted to`123`.
The default behavior is still coercion, since this would otherwise be a breaking change.
=> Add coerceNumbers flag to routes

CHANGELOG.md
This is basically the same stuff (give or take a few missing things), but with the changes separated into those that happened between the various versions that people have been using.
Hopefully this makes it easier to see what needs to be done to upgrade a project to 2.0.
I've added entries for the breaking change in the type signature of `connectRoutes` made in `@rudy`, and for some of the recent bug fixes.
=> Separate changelog into 1.0, next, rudy, and 2.0 versions

.travis.yml, README.md, __tests__/connectRoutes.js, __tests__/pure-utils.js, docs/migration.md, docs/redux-persist.md, package.json, src/pure-utils/actionToPath.js
when upgrading to RFR 2.0, found that it doesn't support node 6 anymore, but the only offender seems to be using `Object.entries`, I think it will save everyone's time, if we just keep supporting node 6, since effort is small and this is in maintenance stage
=> fix node 6 support, remove usage of Object.entries

__tests__/pure-utils.js, docs/connectRoutes.md, src/flow-types.js, src/pure-utils/pathToAction.js
/foo route's path is matching /foo and /foo/ urls by default. Setting strict option to true makes
/foo match /foo url but not /foo/.
fix faceyspacey#312
=> feat(connectRoutes): add strict option for trailing delimiter

src/connectRoutes.js
Hi, this is my first time submitting a contribution to this repository. I ran into this issue when using this package and tracked it down to this conditional. Here's my use case and why I'm proposing this contribution.
I wanted to update the scroll after async content has been loaded from a route thunk.
In my SSR app, when requesting the page from the server, it awaits all the route thunks before rendering the app and sending to the user. However, if you are routed from the front end, the app rightly renders before all thunks are complete. One of my thunks was fetching content for the page, and so the scroll would be updated before the content shifted the layout of the page, winding up in the scroll being in the wrong place.
The answer: update the scroll manually after the content is …
=> Fixes exported updateScroll function if set to manual

docs/connectRoutes.md, src/flow-types.js
From docs https://github.com/faceyspacey/redux-first-router/tree/master/examples/thunks#pathless-routes
> A pathless route is a `routesMap` entry without a `path`
=> fix: RouterObjer.path should be optional

__tests__/pure-utils.js, src/connectRoutes.js, src/pure-utils/confirmLeave.js
Hey!
This PR introduces support of usage scenarios when initial route is needed to be location-blocking and loaded partially (without `confirmLeave` property) on init but it's updated (adding `confirmLeave`) using `addRoutes()` later. It's necessary if the following conditions are combined:
- router related code-splitting is used;
- SSR is used;
- only serializable parts of current route's config are sent from the server (such as `path` property);
- full implementation of the routes is loaded and applied with subsequent JavaScript chunks;
- current route must block the navigation (`confirmLeave()` is present on route's full config).
We use this technique at [fish.travel](https://fish.travel) right now.
Also, [`@oopscurity/redux-first-router@2.1.2`](https://www.npmjs.com/package/@oopscurity …
=> fix(confirmLeave): update current route's history blocking after "addRoutes"

src/reducer/createLocationReducer.js
For fixing #372 
Without this, if you navigate to same route with same pathname but different query parameters, query params don't update since this if block gets triggered due to initialstate.location being undefined.
```    
route &&
!action.error &&
(typeof route === 'string' || route.path) &&
(action.meta.location.current.pathname === state.pathname &&
action.meta.location.current.search === state.search &&
action.meta.location.kind !== state.kind
)
) {
return {
...state,
kind: action.meta.location.kind
}
}
```
this issue happens from transitioning from http://localhost:8000/?category_id=1&page=1&sort_by=ean%3AASC to http://localhost:8000/ using NavLink from redux-first-router-link
=> Make sure getInitialState return an object with search

src/pure-utils/confirmLeave.js
Fixes https://github.com/faceyspacey/redux-first-router/issues/426
When using confirmLeave in the routesMap, the action passed in the function doesn't contain any other data that's in the search part of the location.
Since in [pathToAction.js](https://github.com/faceyspacey/redux-first-router/blob/391f344ede84ed12ee15bc55c800b2962502ec8e/src/pure-utils/pathToAction.js#L17) we clearly expect a search part in the location:
```javascript
const parts = pathname.split('?')
const search = parts[1]
const query = search && serializer && serializer.parse(search)
```
This seemed like a bug, so that explains the reason for this PR 😄
=> Fix: Include search params in pathname

examples/thunks/README.md
Prior to this change, the link to the Star Wars API in the thunks example README was referencing an old URL.
This change updates the URL to the new "https://swapi.dev" domain.
Fixes #448
=> Update Star Wars API link in thunks README
