faceyspacey/redux-first-router

__tests__/__snapshots__/connectRoutes.js.snap
src/connectRoutes.js

Fix issue exposed in https://github.com/faceyspacey/redux-first-router/issues/65#issuecomment-320516244

Redirect prev

---

flow-typed/npm/react-redux_v4.x.x.js
package.json
yarn.lock

Upgrades flow dependency, pulls updated react-redux libdef compatible with new React.Element signatures introduced in v.0.53.0.

fix($deps): upgrade flow to v0.54.1

---

docs/connectRoutes.md

Basic doc + minor fixes (missing opening backtick, removed wrong option count)

Add querySerializer option to connectRoutes doc

---

docs/connectRoutes.md

Updates docs to be in sync with the new code adding the "bag" argument to on* router options.

fix($docs): update connectRoutes.md with new bag arguments

---

docs/server-rendering.md

Fixed some wrong parts in sample codes.

docs(server-rendering): fix some wrong parts in sample codes

---

.snyk
package.json
yarn.lock

Updating deps that cause a security warning when undergoing auidts

chore: Dependency Updates

---

README.md
docs/query-strings.md
docs/server-rendering.md
src/index.js
troubleshooting.md

looks like its all documentation.

Merge the latest master into rudy

---

src/connectRoutes.js

Fix crash in canGoBack and canGoForward

---

README.md

I've also fixed the link as it said here twice before and was using html rather than pure markdown

A few typo fixes to Readme

---

.babelrc
package.json
src/action-creators/middlewareCreateAction.js
yarn.lock

When in Dev, `console.error` when a catch is thrown

fix(middlewareCreateAction): Error logging

---

README.md
docs/migration.md
package.json

Small content block describing how to move from v1 to v2

docs(readme): Migration documentation

---

.babelrc
README.md
package.json

Now uses https to avoid mixed content warnings

docs(badges): Fixed min node version badge 

---

docs/migration.md

https://github.com/faceyspacey/redux-first-router/issues/305#issuecomment-429424364

docs(readme): Improve migration doc

---

README.md
docs/migration.md
package.json
yarn.lock

Enhanced migration docs and general readmes

docs: Improved Docs

---

docs/connectRoutes.md

To match https://github.com/faceyspacey/redux-first-router/blob/master/src/flow-types.js#L76

fix: Fixed signature of restoreScroll

---

package.json

chore: use prepare instead of prePublish

---

.npmignore

Check current files: https://unpkg.com/redux-first-router@2.1.1/

Remove unnecessary files from a package file

---

README.md

Having the docs link buried in the text was making it hard to find the documentation.  Inlined those links with a preview.  Various cleanups for things like broken images and outdated new version release, general formatting for readability.

Made the readme easier to read

---

package-lock.json
package.json

Hi,
Im playing around trying to create an spa without any bundler only using [pika web](https://github.com/pikapkg/web), for which I need ESM support.
I think this can halp others as well.
Regards,
Mictian

Add esm support

---

README.md

saw the readme image was broken, hopefully this fixes it.  shows as fixing it in preview, but github image references can be a little weird.

attempt to fix readme image
